### PR TITLE
fixed helper image path bug

### PR DESCRIPTION
**Pull request by onlinetocode**
The image_path helper has lead to wrong paths because it seems that the jquery raty library takes care of the path with help of the data-attributes.

It merges the `data-star-path value` with for example the `data-star-on value`. If we use the `image_path` method to create the value it results in a wrong path:

```ruby
star_path    = options[:star_path]    || '/assets'
star_on      = options[:star_on]      || image_path('star-on.png')
```
leads to the wrong path `/assets/assets/star-on.jpg`
```ruby
star_path    = options[:star_path]    || '/assets'
star_on      = options[:star_on]      || image_path('/star-on.png')
```
leads to the wrong path `/assets//star-on.jpg`
```ruby
star_path    = options[:star_path]    || '/assets'
star_on      = options[:star_on]      || 'star-on.png')
```
leads to the correct path `/assets/star-on.png`

### CODE REVIEW

**Comment by wazery** [comment]
Thanks @onlinetocode for your PR, I will review and merge today. Actually there is a huge PR that has a commit fixing the exact same issue, I will merge yours, and handle the conflict later.

**Comment by onlinetocode** [comment]
It seems that it's not working in production because precompiling expands the name of the assets with a signature. So I have to use image_path helper to get the correct filename.

e.g. `star-on.jpg` becomes `star-on-078fb9638cc0bc92bfa6c68332887622.jpg`

So don't merge this pull request. I will fix this later today and will post a comment here when it's done.

**Comment by onlinetocode** [comment]
Now it works in development and in production!

**Comment by wazery** [comment]
@onlinetocode Yes, that is implemented in another PR with some more details, thanks for your PR anyway!

**Pull request closed without merging**
