### PR TITLE
Update jquery.raty.js.erb

### PR DESCRIPTION
**Pull request by veduket**
Changes on lines 727,728, 748,749 and 750 
Original 
 cancelOff    : '<%= asset_path('cancel-off.png') %>',
 cancelOn     : '<%= asset_path('cancel-on.png') %>',

Changed
  cancelOff    : '<%= asset_path("cancel-off.png") %>',
  cancelOn     : '<%= asset_path("cancel-on.png") %>',

### CODE REVIEW

**Comment by wazery** [comment]
@veduket What is the benefit of this change?

**Comment by veduket** [comment]
I had an error while displaying the stars in the view and the JavaScript console pointed out that there was a syntax error on those lines. Two constitutive single quotes, I changed the second quote and it worked.

**Comment by wazery** [comment]
Oh!, anyways, thanks for the PR, will merge now.

**Comment by wazery** [comment]
Please let me know if you have any refactoring proposals, so I can add you as a collaborator in the gem.

**Comment by veduket** [comment]
@wazery Great! Thanks for the gem too. Of course I will be happy.

**Comment by wazery** [comment]
I added you, feel free to contribute to the gem :smiley: .

**Pull request merged**
